### PR TITLE
jetty-runner-shaded submodule

### PR DESCRIPTION
**Pull request by xBis7**
https://github.com/G-Research/gr-oss/issues/736

### CODE REVIEW

**Comment by xBis7** [comment]
@GeorgeJahad

**Comment by xBis7** [comment]
`TestLdapAtnProviderWithMiniDS.java` is failing with this error

```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.apache.directory.server.core.api.event.ExpressionEvaluator.<init>(ExpressionEvaluator.java:73)
	at org.apache.directory.server.core.api.subtree.SubtreeEvaluator.<init>(SubtreeEvaluator.java:52)
	at org.apache.directory.server.core.DefaultDirectoryService.<init>(DefaultDirectoryService.java:315)
	at org.apache.directory.server.core.factory.DefaultDirectoryServiceFactory.<init>(DefaultDirectoryServiceFactory.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.apache.directory.server.core.factory.DSAnnotationProcessor.createDS(DSAnnotationProcessor.java:89)
	at org.apache.directory.server.core.factory.DSAnnotationProcessor.getDirectoryService(DSAnnotationProcessor.java:328)
	at org.apache.directory.server.core.integ.FrameworkRunner.run(FrameworkRunner.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
```

`org.apache.directory.server.core` isn't the package that was on the error we were getting without the new jetty jar. This is caused by something else.

**Comment by xBis7** [comment]
```
❯ find ~/.m2/repository | grep jetty-runner
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded/3.1.3-with-backport
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded/3.1.3-with-backport/jetty-runner-shaded-3.1.3-with-backport.jar
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded/3.1.3-with-backport/_remote.repositories
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded/3.1.3-with-backport/jetty-runner-shaded-3.1.3-with-backport.pom
/home/xbis/.m2/repository/org/apache/hive/jetty-runner-shaded/maven-metadata-local.xml
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217/jetty-runner-9.4.51.v20230217.jar.sha1
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217/_remote.repositories
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217/jetty-runner-9.4.51.v20230217.pom
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217/jetty-runner-9.4.51.v20230217.pom.sha1
/home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/9.4.51.v20230217/jetty-runner-9.4.51.v20230217.jar

❯ rm -rf /home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner/* 
zsh: sure you want to delete all the files in /home/xbis/.m2/repository/org/eclipse/jetty/jetty-runner [yn]? y
```

If I delete all the jetty-runner jars and keep only the new ones, then the test passes. If I reload the project on the IDE, then it's generating the `jetty-runner` jars. Somewhere in the project there is a dependency that is bringing the `jetty-jar` into the `.m2/repository`. If we exclude it globally, we should be good to go. If any new issues arise in any module, we will include the new jetty-jar there as a dependency.

**Comment by xBis7** [comment]
I didn't exclude it globally because no other tests were failing and I was afraid that I would break things without needing to. Just excluding it from the `service` module, fixed it.

The test is no longer failing.

**Review by GeorgeJahad — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
